In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df0 = pd.read_csv('/content/drive/MyDrive/antifraud/dataset/df0_with_embeddings.csv')
df1 = pd.read_csv('/content/drive/MyDrive/antifraud/dataset/df1_with_embeddings.csv')
df0_test = pd.read_csv('/content/drive/MyDrive/antifraud/test/df0_with_embeddings.csv')
df1_test = pd.read_csv('/content/drive/MyDrive/antifraud/test/df1_with_embeddings.csv')

In [ ]:
df1.dropna(inplace=True)
df1_test.dropna(inplace=True)

In [ ]:
df0 = df0.reset_index()
df1 = df1.reset_index()
df0_test = df0_test.reset_index()
df1_test = df1_test.reset_index()


df0['Target'] = pd.Series([0]*df0.shape[0])
df1['Target'] = pd.Series([1]*df1.shape[0])
df0_test['Target'] = pd.Series([0]*df0_test.shape[0])
df1_test['Target'] = pd.Series([1]*df1_test.shape[0])

In [ ]:
df = pd.concat([df0, df1], ignore_index=True)
df = df.sample(frac=1)

In [ ]:
df1_test['Target'] = pd.Series([1]*df1_test.shape[0])

In [ ]:
df_test = pd.concat([df0_test, df1_test], ignore_index=True)
df_test = df_test.sample(frac=1)

In [ ]:
from sklearn import svm

In [ ]:
from sklearn.model_selection import cross_val_score
clf = svm.SVC()
scores_acc = cross_val_score(clf, df.drop(columns=['Path', 'Text', 'Target', 'index']), df.Target, cv=5, scoring="accuracy")
print(scores_acc, scores_acc.mean().round(3))

[0.97398217 0.96976632 0.97506325 0.97217203 0.97181063] 0.973


In [ ]:
scores_acc = cross_val_score(clf, df.drop(columns=['Path', 'Text', 'Target', 'index']), df.Target, cv=5, scoring="precision")
print(scores_acc, scores_acc.mean().round(3))

[0.99010569 0.98759585 0.99012567 0.98918919 0.98984428] 0.989


In [ ]:
scores_acc = cross_val_score(clf, df.drop(columns=['Path', 'Text', 'Target', 'index']), df.Target, cv=5, scoring="recall")
print(scores_acc, scores_acc.mean().round(3))

[0.96240437 0.95715847 0.96437158 0.96       0.95868852] 0.961
